/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modbus.comm0;

import com.digitalpetri.modbus.master.ModbusTcpMaster;
import com.digitalpetri.modbus.master.ModbusTcpMasterConfig;
import com.digitalpetri.modbus.requests.ReadHoldingRegistersRequest;
import com.digitalpetri.modbus.responses.ReadHoldingRegistersResponse;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufUtil;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

public class App {
    static void printf(String format, Object... args) {
        System.out.printf(format, args);
    }

    public static void main(String[] args) throws InterruptedException {
        printf("%-15s%-10.2f\n", "压力(kpa):", 43.4);
        Logger logger = LogManager.getLogger();
        Thread t = new Thread(() -> {
            ModbusTcpMasterConfig cfg = new ModbusTcpMasterConfig.Builder("192.168.1.244")
                    .setPort(502)
                    .build();
            ModbusTcpMaster master = new ModbusTcpMaster(cfg);
            master.connect();
            try {
                int n = 0, max = 10;
                while (n < max) {
                    CompletableFuture<ReadHoldingRegistersResponse> future = master
                            .sendRequest(new ReadHoldingRegistersRequest(0, 5), 0);
                    ReadHoldingRegistersResponse response = future.get();
                    ByteBuf buf = response.getRegisters();
                    System.out.println(ByteBufUtil.hexDump(buf));
                    Thread.sleep(500);
                    n++;
                }
                Future<?> shutdownFuture = master.disconnect();
                shutdownFuture.get();
            } catch (ExecutionException | InterruptedException e) {
                e.printStackTrace();
            }
        });
        t.start();
        t.join();
        logger.error("Hello");
    }
}
